<a href="https://colab.research.google.com/github/Gouri1419/ml_with_flask/blob/main/uploadfiles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
uploaded=files.upload()
aaa=list(uploaded.keys())[0]


Saving customers-100.csv to customers-100 (1).csv


In [ ]:
from google.colab import files
import pandas as pd
uploaded=files.upload()
aaa=list(uploaded.keys())[0]

# Read the uploaded file into a pandas DataFrame
df = pd.read_csv(aaa) # Assuming the uploaded file is a CSV

# Now you can use df
df.iloc[[1,3,5,6]]

Saving customers-100.csv to customers-100 (2).csv


Index      Customer Id First Name Last Name  \
1      2  1Ef7b82A4CAAD10    Preston    Lozano   
3      4  5Cef8BFA16c5e3c      Linda     Olsen   
5      6  2d08FB17EE273F4      Aimee     Downs   
6      7  EA4d384DfDbBf77     Darren      Peck   

                           Company               City                 Country  \
1                      Vega-Gentry  East Jimmychester                Djibouti   
3  Dominguez, Mcmillan and Donovan         Bensonview      Dominican Republic   
5                     Steele Group      Chavezborough  Bosnia and Herzegovina   
6     Lester, Woodard and Mitchell           Lake Ana        Pitcairn Islands   

                  Phone 1               Phone 2                        Email  \
1              5153435776      686-620-1820x944              vmata@colon.com   
3  001-808-617-6467x12895       +1-813-324-8756  stanleyblackwell@benson.org   
5     (283)437-3886x88321          999-728-1637          louis27@gilbert.com   
6      (496)452-6181x3291  +1-247-266-0963x4995          tgates@cantrell.com   

  Subscription Date                     Website  
1        2021-04-23       http://www.hobbs.com/  
3        2020-06-02  http://www.good-lyons.com/  
5        2020-02-25      http://www.berger.net/  
6        2021-08-24         https://www.le.com/

In [ ]:
df.iloc[[7,10,25,28,56]]


Index      Customer Id First Name    Last Name  \
7       8  0e04AFde9f225dE      Brett       Mullen   
10     11  216E205d6eBb815       Carl    Schroeder   
25     26  09D7D7C8Fe09aea     Marcus        Moody   
28     29  3B5dAAFA41AFa22   Stefanie  Fitzpatrick   
56     57  c8FE57cBBdCDcb2    Phyllis    Maldonado   

                         Company          City  \
7   Sanford, Davenport and Giles       Kimport   
10    Oconnell, Meza and Everett  Shannonville   
25                     Giles Ltd   Kaitlyntown   
28                 Santana-Duran  Acevedoville   
56                     Costa PLC  Lake Whitney   

                             Country               Phone 1  \
7                           Bulgaria  001-583-352-7197x297   
10                          Guernsey      637-854-0256x825   
25                            Panama          674-677-8623   
28  Saint Vincent and the Grenadines         (752)776-3286   
56                  Saint Barthelemy            4500370767   

                  Phone 2                            Email Subscription Date  \
7        001-333-145-0369                  asnow@colon.com        2021-04-12   
10       114.336.0784x788               kirksalas@webb.com        2021-10-20   
25       909-277-5485x566  donnamullins@norris-barrett.org        2022-05-24   
28  +1-472-021-4814x85074               wterrell@clark.com        2020-07-30   
56   001-508-064-6725x017          yhanson@warner-diaz.org        2021-01-25   

                        Website  
7   https://hammond-ramsey.com/  
10  https://simmons-hurley.com/  
25       https://www.curry.com/  
28          https://meyers.com/  
56      http://www.bernard.com/

In [ ]:
df.drop('Phone 2',axis=1)

Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...                ...   
95                        Carey LLC       East Richard   
96            Ware, Burns and Oneal       New Bradview   
97                    Schmitt-Jones         Ortegaland   
98               Fitzgerald-Harrell    Lake Elijahview   
99               Le, Nash and Cross          Judymouth   

                       Country                 Phone 1  \
0                        Chile            229.077.5154   
1                     Djibouti              5153435776   
2          Antigua and Barbuda         +1-539-402-0259   
3           Dominican Republic  001-808-617-6467x12895   
4   Slovakia (Slovak Republic)  001-234-203-0635x76146   
..                         ...                     ...   
95                      Guyana     (188)169-1674x58692   
96                   Sri Lanka         +1-846-706-2218   
97             Solomon Islands    +1-753-067-8419x7170   
98                       Aruba           (530)311-9786   
99                    Honduras           (753)813-6941   

                             Email Subscription Date  \
0         zunigavanessa@smith.info        2020-08-24   
1                  vmata@colon.com        2021-04-23   
2              beckycarr@hogan.com        2020-03-25   
3      stanleyblackwell@benson.org        2020-06-02   
4          colinalvarado@miles.net        2021-04-17   
..                             ...               ...   
95                hhart@jensen.com        2022-01-30   
96               vkemp@ferrell.com        2021-07-10   
97                swagner@kane.org        2021-09-18   
98  mccarthystephen@horn-green.biz        2021-08-11   
99          colleen91@faulkner.biz        2020-03-11   

                              Website  
0          http://www.stephenson.com/  
1               http://www.hobbs.com/  
2            http://www.lawrence.com/  
3          http://www.good-lyons.com/  
4         https://goodwin-ingram.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[100 rows x 11 columns]

In [ ]:
df.isnull()


Index  Customer Id  First Name  Last Name  Company   City  Country  \
0   False        False       False      False    False  False    False   
1   False        False       False      False    False  False    False   
2   False        False       False      False    False  False    False   
3   False        False       False      False    False  False    False   
4   False        False       False      False    False  False    False   
..    ...          ...         ...        ...      ...    ...      ...   
95  False        False       False      False    False  False    False   
96  False        False       False      False    False  False    False   
97  False        False       False      False    False  False    False   
98  False        False       False      False    False  False    False   
99  False        False       False      False    False  False    False   

    Phone 1  Phone 2  Email  Subscription Date  Website  
0     False    False  False              False    False  
1     False    False  False              False    False  
2     False    False  False              False    False  
3     False    False  False              False    False  
4     False    False  False              False    False  
..      ...      ...    ...                ...      ...  
95    False    False  False              False    False  
96    False    False  False              False    False  
97    False    False  False              False    False  
98    False    False  False              False    False  
99    False    False  False              False    False  

[100 rows x 12 columns]

In [ ]:
dict1 = {'Customer_id':[1,2,3,4,5,6]}

Saving customers-100.csv to customers-100 (3).csv


KeyError: 'Costumer_id'

In [ ]:
df.iloc[5:61,4:7]

Company                 City  \
5                      Steele Group        Chavezborough   
6      Lester, Woodard and Mitchell             Lake Ana   
7      Sanford, Davenport and Giles              Kimport   
8                    Browning-Simon         Robersonstad   
9                      Beck-Hendrix           Elaineberg   
10       Oconnell, Meza and Everett         Shannonville   
11        Hoffman, Reed and Mcclain          East Andrea   
12                   Graham-Francis    South Joannamouth   
13                   Carpenter-Cook             Jodyberg   
14                   Carter-Hancock            Burchbury   
15               Singleton and Sons         Desireeshire   
16                  Winters-Mendoza    West Adriennestad   
17                    Valentine LLC          Lake Leslie   
18                        Simon LLC           Harmonview   
19                   Mays-Mccormick           Jamesshire   
20                    Patterson Inc           East Carly   
21       Manning, Hester and Arroyo          South Alvin   
22                   Greer and Sons         Brittanyview   
23                  Watts-Donaldson        Veronicamouth   
24                       Tucker LLC           Bryanville   
25                        Giles Ltd          Kaitlyntown   
26                    Simmons Group         Michealshire   
27        Hinton, Chaney and Stokes    South Marissatown   
28                    Santana-Duran         Acevedoville   
29                       Sawyer PLC         North Harold   
30      Acosta, Petersen and Morrow          West Samuel   
31                      Mcgee Group    Cunninghamborough   
32                   Adkins-Salinas        Port Annatown   
33                    Herrera Group          New Kaitlyn   
34        Waters, Chase and Aguilar     West Marthaburgh   
35       Palmer, Barnes and Houston          East Teresa   
36                       Jordan Ltd         South Hunter   
37                  Glover and Sons         South Walter   
38                    Huerta-Mclean            Poolefurt   
39                     Anderson Ltd            West John   
40                       Monroe PLC          West Darius   
41                 Kaufman and Sons        North Jimstad   
42                  Perkins-Trevino  East Rebekahborough   
43                        Cross PLC           North Drew   
44  Herrera, Shepherd and Underwood      Lake Lindaburgh   
45       Price, Sexton and Mcdaniel        Gwendolynview   
46                    Short-Wiggins        Zimmermanland   
47        Brennan, Acosta and Ramos       North Kerriton   
48                 Osborne-Erickson    North Eileenville   
49       Hobbs, Garrett and Sanford      Port Sergiofort   
50          Phelps, Forbes and Koch       New Alberttown   
51          May, Goodwin and Martin        South Jasmine   
52     Christian, Winters and Ellis            Cowanfort   
53                         Byrd Inc          New Deborah   
54        Nixon, Blackwell and Sosa            Wallstown   
55                       Montes PLC    Lake Ellenchester   
56                        Costa PLC         Lake Whitney   
57                        Novak LLC       East Jaredbury   
58           Moore, Mccoy and Glass           Selenabury   
59                        Petty Ltd            Huangfort   
60       Brennan, Camacho and Tapia      East Pennyshire   

                                         Country  
5                         Bosnia and Herzegovina  
6                               Pitcairn Islands  
7                                       Bulgaria  
8                                         Cyprus  
9                                    Timor-Leste  
10                                      Guernsey  
11                                       Vietnam  
12                                          Togo  
13                                     Sri Lanka  
14                                     Singapore  
15                                          Om

In [ ]:
dict1={'Customer_id':[1,2,3,4,5,6],'Product':['Television','Television','Oven','Oven','Oven','Television']}
df1=pd.DataFrame(dict1)
df1

Customer_id     Product
0            1  Television
1            2  Television
2            3        Oven
3            4        Oven
4            5        Oven
5            6  Television

Customer_id     Product
0            1  Television
1            2  Television
2            3        Oven
3            4        Oven
4            5        Oven
5            6  Television

In [ ]:
dict1={'Customer_id':[1,2,3,4,5,6],'State':['California','Texas','New York','Indiana','Florida','California']}
df2=pd.DataFrame(dict1)
df2

Customer_id       State
0            1  California
1            2       Texas
2            3    New York
3            4     Indiana
4            5     Florida
5            6  California

In [ ]:
inner_join_df=pd.merge(df1,df2,on='Customer_id',how='inner')
inner_join_df

Customer_id     Product       State
0            1  Television  California
1            2  Television       Texas
2            3        Oven    New York
3            4        Oven     Indiana
4            5        Oven     Florida
5            6  Television  California

In [ ]:
outer_join_df=pd.merge(df1,df2,on='Customer_id',how='outer')
outer_join_df

Customer_id     Product       State
0            1  Television  California
1            2  Television       Texas
2            3        Oven    New York
3            4        Oven     Indiana
4            5        Oven     Florida
5            6  Television  California

In [ ]:
left_join_df=pd.merge(df1,df2,on='Customer_id',how='left')
left_join_df


Customer_id     Product       State
0            1  Television  California
1            2  Television       Texas
2            3        Oven    New York
3            4        Oven     Indiana
4            5        Oven     Florida
5            6  Television  California

In [ ]:
right_join_df=pd.merge(df1,df2,on='Customer_id',how='right')
right_join_df


Customer_id     Product       State
0            1  Television  California
1            2  Television       Texas
2            3        Oven    New York
3            4        Oven     Indiana
4            5        Oven     Florida
5            6  Television  California

In [ ]:
inner_join_df=pd.merge(df1,df2,on='Product',how='inner')
inner_join_df

KeyError: 'Product'

In [ ]:
# prompt: create two dataframes int the first dataframe product and customer name in the second dataframe product name and price try to join with product name

dict1 = {'Product': ['Television', 'Television', 'Oven', 'Oven', 'Oven', 'Television'],
         'Customer Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank']}
df1 = pd.DataFrame(dict1)

dict2 = {'Product Name': ['Television', 'Oven', 'Refrigerator'],
         'Price': [1000, 500, 1200]}
df2 = pd.DataFrame(dict2)

# Merge the two dataframes on 'Product' and 'Product Name'
merged_df = pd.merge(df1, df2, left_on='Product', right_on='Product Name', how='inner')
merged_df

Product Customer Name Product Name  Price
0  Television         Alice   Television   1000
1  Television           Bob   Television   1000
2        Oven       Charlie         Oven    500
3        Oven         David         Oven    500
4        Oven           Eve         Oven    500
5  Television         Frank   Television   1000

In [ ]:
import pandas as pd
import numpy as np
# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
'Mahindra', 'Maruti', 'Hyundai',
'Renault', 'Tata', 'Maruti'],
'Year': [2012, 2014, 2011, 2015, 2012,
2016, 2014, 2018, 2019],
'Kms Driven': [50000, 30000, 60000,
25000, 10000, 46000,
31000, 15000, 12000],
'City': ['Gurgaon', np.nan, 'Mumbai',
'Delhi', 'Mumbai', 'Delhi',
'Mumbai', 'Chennai', 'Ghaziabad'],
'Mileage': [28, 27, 25, 26, 28,
29, 24, 21, 24]})
# displaying the DataFrame
display(data)
#data.isnull()

Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000        NaN       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24

In [ ]:
import numpy as np


arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
import numpy as np
array = np.arange(40).reshape(4,10)
print(array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,23])
print(arr[2] + arr[3])
print(arr[0] + arr[1])
print(arr[5] + arr[7])

7
3
14


In [ ]:
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
'Mahindra', 'Maruti', 'Hyundai',
'Renault', 'Tata', 'Maruti'],
'Year': [2012, 2014, 2011, 2015, 2012,
2016, 2014, 2018, 2019],
'Kms Driven': [50000, 30000, 60000,
25000, 10000, 46000,
31000, 15000, 12000],
'City': ['Gurgaon', np.nan, 'Mumbai',
'Delhi', 'Mumbai', 'Delhi',
'Mumbai', 'Chennai', 'Ghaziabad'],
'Mileage': [28, 27, 25, 26, 28,
29, 24, 21, 24]})
# displaying the DataFrame
display(data)
#data.isnull()


Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000        NaN       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24